apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: {{ .Values.storage.storageSize }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.storage.storageClassName }}
  local:
    path: {{ .Values.storage.hostPathPrefix }}/{{ .Values.storage.volume1 }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.node }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-cleanup-job"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cleanup-job
        image: "declanf/pvc-cleanup:latest"
        volumeMounts:
          - name: pv-1-claim
            mountPath: /vol1
      volumes:
        - name: pv-1-claim
          persistentVolumeClaim:
            claimName: pv-1-claim